/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ルーム作成 */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ルーム情報取得 */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ルーム参加 */
        post: operations["joinRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ゲーム開始 */
        post: operations["startGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** プレイヤーアクション実行 */
        post: operations["executeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ゲーム状態取得 */
        get: operations["getGameState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRoomRequest: {
            /** @example Player1 */
            hostName: string;
            /** @example 10 */
            smallBlind: number;
            /** @example 20 */
            bigBlind: number;
        };
        CreateRoomResponse: {
            /** @example room-123abc */
            roomId: string;
            /** @example player-456def */
            hostId: string;
        };
        RoomResponse: {
            id: string;
            hostId: string;
            players: components["schemas"]["PlayerInfo"][];
            /** @enum {string} */
            state: "waiting" | "in_progress" | "ended";
            smallBlind: number;
            bigBlind: number;
            dealerIndex?: number;
        };
        JoinRoomRequest: {
            /** @example Player2 */
            playerName: string;
        };
        JoinRoomResponse: {
            roomId: string;
            playerId: string;
            players: components["schemas"]["PlayerInfo"][];
        };
        ActionRequest: {
            /** @example player-123 */
            playerId: string;
            action: {
                /**
                 * @example raise
                 * @enum {string}
                 */
                type: "fold" | "check" | "call" | "raise" | "allin" | "acknowledge";
                /** @example 50 */
                amount?: number;
            };
        };
        ActionResponse: {
            success: boolean;
            gameState: components["schemas"]["GameState"];
            message?: string;
        };
        GameStateResponse: {
            gameState: components["schemas"]["GameState"];
        };
        GameState: {
            /**
             * @example preflop
             * @enum {string}
             */
            stage: "preflop" | "flop" | "turn" | "river" | "showdown" | "ended";
            /** @example 0 */
            dealerIndex: number;
            /** @example 1 */
            currentBettorIndex: number;
            /** @example 20 */
            currentBet: number;
            /** @example 20 */
            minRaiseAmount?: number;
            /** @example 30 */
            totalPot: number;
            /** @example [] */
            communityCards: string[];
            /**
             * @description ゲームがプレイヤーからの確認応答を待っているかどうか
             * @example false
             */
            waitingForAck: boolean;
            ackState?: components["schemas"]["AckState"];
            players: components["schemas"]["PlayerState"][];
            pots?: components["schemas"]["Pot"][];
        };
        PlayerInfo: {
            /** @example player-123 */
            id: string;
            /** @example Player1 */
            name: string;
            /** @example 1000 */
            chips: number;
            /** @example 0 */
            seat: number;
        };
        PlayerState: {
            id: string;
            name: string;
            chips: number;
            seat: number;
            /** @description 現在のストリートのベット額 */
            bet: number;
            /** @description 累積ベット額（全ストリート） */
            cumulativeBet: number;
            isFolded: boolean;
            hasActed: boolean;
            /**
             * @description プレイヤー本人のみ取得可能
             * @example [
             *       "As",
             *       "Kh"
             *     ]
             */
            hand?: string[];
        };
        Pot: {
            amount: number;
            eligiblePlayers: string[];
        };
        /** @description 確認応答の状態（waitingForAck=trueの場合のみ存在） */
        AckState: {
            /**
             * @description 確認応答を待っているプレイヤーIDのリスト
             * @example [
             *       "player-123",
             *       "player-456"
             *     ]
             */
            expectedAcks: string[];
            /**
             * @description 確認応答を受け取ったプレイヤーIDのリスト
             * @example [
             *       "player-123"
             *     ]
             */
            receivedAcks: string[];
            /**
             * @description 確認応答待ち開始時刻（Unix timestamp）
             * @example 1733270400000
             */
            startedAt: number;
            /**
             * @description 確認応答を待っている理由
             * @example Waiting for showdown acknowledgment
             */
            description: string;
        };
        ErrorResponse: {
            error: {
                /** @example INVALID_ACTION */
                code: string;
                /** @example プレイヤーがすでにフォールドしています */
                message: string;
                details?: Record<string, never>;
            };
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description リソースが見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description サーバー内部エラー */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description ルームID */
        RoomId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description ルーム作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoomResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルームID */
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ルーム情報取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    joinRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルームID */
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRoomRequest"];
            };
        };
        responses: {
            /** @description ルーム参加成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRoomResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    startGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルームID */
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゲーム開始成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    executeAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルームID */
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description アクション実行成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getGameState: {
        parameters: {
            query: {
                /** @description プレイヤーID（手札情報のフィルタリング用） */
                playerId: string;
            };
            header?: never;
            path: {
                /** @description ルームID */
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゲーム状態取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
